spring:
  datasource:
    driverclassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum
    username: root
    password: Hellen@15
  jpa:
    properties:
      hibernate:
        show sql: true
        format sql: true

  h2:
    console:
      enabled: true
jwt:
  secret: suaChaveSuperSecretaComMaisDe32Caracteres1234
  #mvn spring-boot:run "-Dspring.profiles.active=prod"

