spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    host: localhost
    port: 6379
  h2:
    console:
      enabled: true
jwt:
  secret: suaChaveSuperSecretaComMaisDe32Caracteres1234
