name: CI

on:
  push:
    branches:
      - '*'

jobs:
  in-docker_test:
    name: Testes automatizados
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache de dependências Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Check MySQL Service
        run: mysql -u root -proot -e "SHOW DATABASES;"

      - name: Wait for MySQL
        run: until mysqladmin ping -h 127.0.0.1 --silent; do echo "Waiting for MySQL..."; sleep 5; done;

      - name: Executar testes
        run: mvn -B clean test

      - name: Run tests with debug
        if: failure()
        run: mvn test -X

      - name: Exibir Logs
        if: failure()
        run: cat target/surefire-reports/*.txt
